[НАСТРОЙКИ]
;==========КЛЮЧ==========
API_KEY = <ВСТАВИТЬ КЛЮЧ с сайта https://ofdata.ru/api/contracts>


; если возвращает таблицу из пары строк значит ошибка в запросе,
; скорее всего ИНН ОГРН правильный но фз не тот, или роль не та, 
; либо компания таким не занималась


; указывать OGRN или INN одно из двух обязательно
OGRN = 1027700198767

INN = 

; можно указать вместе с инн, не отдельно
KPP = 


; Обязательно указать по какому фз закупка, иначе будет ошибка
; 44
; 223 с 2019 не публекуется
; 94

LAW = 44


; Роль участника закупки, по которой будет осуществляться поиск.
; customer - заказчик
; supplier - поставщик

ROLE = supplier


; Кол-во записей в таблице формирующейся таблице, 
; ВАЖНО! Максимальное значение 100,
; если указать больше, то будет ошибка
; Если нужны значения с 101 до 201,
; то нужно указать LIMIT = 100 и PAGE = 2
; и тд

LIMIT = 100

PAGE = 


; сортировка результатов
; можно указать
; date для сортировки по дате подписания контракта, по возрастанию,
; -date для сортировки по дате подписания контракта, по убыванию,
; price для сортировки по цене контракта, по возрастанию,
; -price для сортировки по цене контракта, по убыванию.
; ВАЖНО!
; это не просто переворот страницы, а именно сортировка сырых данных
; если данных больше 100 а сортировку поставить по цене,
; то в итоговой таблице свежих закупок может не быть

SORT = -date